---
title: "4.a. Climate Vulnerability"
author: "Britsch / Stoll"
date: "11/5/2021"
output: html_document
---


###Source Code
####author: "Christophe Nicault"
####date: "15/10/2021"
#####https://github.com/cnicault/tidytuesday/blob/master/2021/2021-42-global_seafood/global_seafood.Rmd


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages}

library(tidyverse)
library(scales)
library(tidytext)
library(glue)
library(patchwork)
library(showtext)
library(ragg)
library(here)
library(RColorBrewer)

font_add_google("Roboto", "roboto")                
font_add_google("Mitr", "mitr")
font_add_google("Khula", "khula")
font_add_google("Share Tech Mono", "techmono")

showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)

```

```{r load_data}

production <- read.csv("/Users/jstoll/OneDrive - University of Maine System/Social_Coasts_Lab/seafood_systems/Data/Processed_Data/ACCSP_Landings_Nonconfidential_Commercial_2007_2020_clean.csv", stringsAsFactors = FALSE)

cats <- read.csv("/Users/jstoll/OneDrive - University of Maine System/Social_Coasts_Lab/seafood_systems/Data/Processed_Data/Species_Categories_Climate_Vulnerability_clean.csv", stringsAsFactors = FALSE)

#adding in confidential values so we get a more accurate picture of total landings for the region
NOAA_conf <- read.csv("/Users/jstoll/OneDrive - University of Maine System/Social_Coasts_Lab/seafood_systems/Data/Processed_Data/NOAA_Landings_Summarized_Confidential_lbs_value_2007_2020_clean.csv", stringsAsFactors = FALSE)


```

Cleaning - production already in long format

```{r clean}

#merging cats and production together
production <- full_join(production, cats, by = "Common.Name")


#merging NOAA and production together
production <- bind_rows(production, NOAA_conf)


#keeping 2010-2020
production <- filter(production, Year >= 2010)

#filling in blanks with NA
production <- production %>%
  mutate(Vulnerability = replace(Vulnerability, Vulnerability == "", NA))

#replacing NA w/ Undefined
production <- production %>%
  mutate(Vulnerability = production$Vulnerability %>% replace_na('Undefined'))

#Adding Confidential
production <- production %>%
  mutate(Vulnerability = replace(Vulnerability, NOAA.category == "Confidential", "Confidential"))

```


```{r prod_evolution}

bck_color <- "grey20"

production_sum <- production %>%
  group_by(Year, Vulnerability) %>%
  summarise(total = sum(Dollars)) %>%
  ungroup()


lines_label <- production_sum %>%
  filter(Year == max(Year)) %>%
  arrange(c("Confidential", "Undefined", "Low", 
            "Moderate","High", "Very High")) %>%
  mutate(cum = cumsum(total),                                  #cumulative value for 2020
         posy = lag(cum, default = 0) + total / 2) %>%         #location of left end of the lines going from graph to labels
  bind_cols(posyend = seq(1e8, 1.375e9, 1.375e9 / 6))          #location of the right end of the lines going from graph to labels          
         

year_list <- tibble(year = seq(2010, 2020, 1))                 #numbers making up the x-axis at the end

fish_order <- production_sum %>%
  filter(Year == max(Year)) %>%
  arrange(c("Very High", "High", "Moderate", 
            "Low", "Undefined", "Confidential")) %>%  
  pull(Vulnerability)                                          #ordering the line graph by total value


axis_p1 <- tibble(x = c(2010, 2014, 2017),                 #years less than the years the values are associated with so they can bee seen. 
                  xend = c(2012, 2016, 2019),                 #years I'm showing in white near the peaks in the graph
                  y = seq(12.5e8, 15e8, 1.25e8),              #locations for those numbers
                  yend = seq(12.5e8, 15e8, 1.25e8),           #ditto (I think?)
                  yend_lab = c("1.25 B", "1.375 B", "1.5 B")) #I created this so we could have simple labels - call this as the "label"    



color_fish <- c()  
color_fish[fish_order] <- colorRampPalette(c("#E31A1C", "#FC4E2A", "#FD8D3C", "#FEB24C", "grey60","grey90"))(6)   #used RColorBrewer ylOrRd palette. use brewer.pal() to get hexes 

production_species_plt <- production_sum %>%
  mutate(Vulnerability = fct_relevel(Vulnerability, fish_order)) %>%          #making NOAA category a factor and reordering it(?)
  ggplot() +
  geom_segment(data = axis_p1, aes(x = x, xend = xend, y = y, yend = yend), 
               color = "white", linetype = "13", size = 0.3, inherit.aes = FALSE) +                                  #size of graph
  geom_text(data = axis_p1, aes(x = x, y = yend, label = yend_lab), 
            color = "white", hjust = 0, nudge_y = 2e7, size = 3, family = "roboto", inherit.aes = FALSE) +           #labels on peaks  
  geom_text(data = year_list, aes(x = year, y = -9e6, label = year), 
            color = "white", hjust = 1.25, vjust = 1, angle = 45,  
            size = 3.5, family = "roboto", inherit.aes = TRUE) +                                                     #new x-axis       
  geom_area(aes(Year, total, fill = Vulnerability), color = "grey60") +                                              #bar graph?
  geom_segment(data = lines_label, aes(x = 2020, xend = 2025, y = posy, yend = posyend, color = Vulnerability)) +    #left-hand lines
  geom_segment(data = lines_label, aes(x = 2028, xend = 2033, y = posyend, yend = posyend, color = Vulnerability)) + #right-hand lines
  geom_label(data = lines_label, aes(x = 2025, y = posyend, label = Vulnerability, color = Vulnerability), 
             fill = bck_color, size = 3.5, family = "khula", nudge_y = 2e7, label.size = 0, 
             hjust = 0, fontface = "bold", inherit.aes = FALSE) +                                                    #spp names near lines
  geom_label(data = lines_label, aes(x = 2025, y = posyend, label = glue("{comma(total)} Dollars"), color = Vulnerability), 
             fill = bck_color, size = 3.5, family = "khula", nudge_y = -3e7, label.size = 0, 
             hjust = 0, fontface = "bold", inherit.aes = FALSE) +                                                    #values near lines
  annotate("text", x = 2010, y = 1.6e9, label = "(A) Value by Climate Vulnerability", 
           family = "khula", size = 5, color = "white", hjust = 0) +                                                 #label
  annotate("text", x = 2033, y = 1.6e9, label = "(B) Total Value of Landings by Climate Vulnerability (2020)", 
           family = "khula", size = 5, color = "white", hjust = 0) +                                                 #label
  scale_fill_manual(values = color_fish) +                                                                          
  scale_color_manual(values = color_fish) +
  scale_x_continuous(limits = c(2010, 2050)) +                                                                       #full size of plot  
  guides(fill = "none", color = "none") +                                         
  theme_void() +                                                                                                     #this and above remove                                                                                                                       built-in lines/axes
  theme(plot.background = element_rect(fill = bck_color, color = NA))                                                #dark-grey background


```

Tricky part : use tidytext::reorder_within to reorder countries by total within each fish group, and place other at the end
to group all countries together and show how much 4 countries account in the world production. 

```{r prod_country}
prod_reorder <- production %>%
  filter(Year == 2020) %>%
  group_by(State, Vulnerability) %>%
  summarise(total = sum(Dollars)) %>%
  ungroup() %>%
  mutate(tot_order = ifelse(Vulnerability == "Undefined", 0, total),  #move other category to the end - not sure if it is relevant here
         Vulnerability = fct_relevel(Vulnerability, rev(fish_order)),  #making NOAA.category a factor and giving it an order (see line 119)
         Entity_wt = reorder_within(State, tot_order, Vulnerability))  #reorder state by total (with other = 0) within NOAA.category groups

prod_colors <- tibble(Color = colorRampPalette(c("#474747", "#ebebeb"))(5),  #selecting colors - took some googling to get right. (#)                                                                                    indicates number of bins
                      State = c("CONNECTICUT", "MAINE", "MASSACHUSETTS", 
                               "NEW HAMPSHIRE", "RHODE ISLAND"))             #names to go with each color


color_within <- prod_reorder %>%
  left_join(prod_colors)                                                     #adding color info to prod_reorder


color_cty <- c() 
color_cty[color_within$Entity_wt] <- color_within$Color                      #not sure about these, but identifying the colors to use


axis_p2 <- tibble(x = c(1, 2, 3, 4, 5, 6),                                  #size of x-axis
                  xend = rep(6.6, 6),                                       #end size
                  y = seq(0, 5.75e8, 1e8),                                  #y-axis
                  yend = seq(0, 5.75e8, 1e8),                               #end of y-axis
                  yend_lab = c("0", "100 M", "200 M", "300 M", "400 M",
                               "500 M"))                                    #simple labels  

spp_labs <- tibble(x2 = c(1, 2, 3, 4, 5, 6),                                #creating the numbers at the end of the bars, and placing them
                   y2 = c(54334714, 18527853, 94320190, 
                          569532837, 371309202, 88689369),                  #placing y based on bar size
                   num_spp = c("n = *", "n = 182", "n = 21",
                               "n = 20", "n = 19", "n = 22"))               #labels 

production_cty_plt <- prod_reorder %>%
  ggplot(aes(as.numeric(Vulnerability), total, fill = Entity_wt)) +                               #plot                       
  geom_segment(data = axis_p2, aes(x = c(1, 3, 4, 4, 4, 4), xend = xend, y = y, yend = yend), 
               color = "white", linetype = "13", size = 0.3, inherit.aes = FALSE) +               #full size
  geom_text(data = axis_p2, aes(x = xend, y = yend, label = yend_lab), 
            color = "white", nudge_x = 0.2, size = 3.5, family = "roboto", inherit.aes = FALSE) + #axis numbering
  geom_text(data = spp_labs, aes(x = x2, y = y2, label = num_spp), size = 3.5,
            family = "roboto", color = "white", nudge_y = 20000000, inherit.aes = FALSE) + 
  geom_col(color = "grey30", width = 0.6, size = 0.2) +                                           #creating columns
  coord_flip() +                                                                                  #rotating
  guides(fill = "none") +                                                                         #removing original background and axis
  scale_fill_manual(values = color_cty) +                                                         #adding in custom color
  theme_void()                                                                                    #removing background (?)

```

Legend

```{r legend}

legend_plt <- prod_colors %>%
  bind_cols(y = seq(5 , 1, -1)) %>%                                             #adding column of #s to the color info
  ggplot()+
  geom_rect(aes(xmin = 1, xmax = 2, ymin = y, ymax = y + 0.8, fill = Color)) +  #Size of legend 
  geom_text(aes(x = 1.5, y = y + 0.4, label = State), 
            size = 3, family = "roboto", color = "white") +                     #labeling and text size
  scale_fill_identity() +                                                       #coloring
  theme_void()                                                                  #removing background

```

Final plot

```{r final_plot}

final <- production_species_plt +                                                                     #line graph 
  inset_element(production_cty_plt, 0.555, 0.033, 1, 0.90) +                                          #bar graph and location coords
  inset_element(legend_plt, 0.9, 0.1, 0.98, 0.4) +                                                    #legend and location coords
  plot_annotation(
    title = "Climate Vulnerability of Species Caught in New England (2010-2020)",
    theme = theme(
      plot.background = element_rect(fill = bck_color, color = NA),
      plot.margin = margin(10, 5, 5, 0),
      plot.title = element_text(family = "mitr", size = 25, color = "white", 
                                hjust = 0.5, vjust = 0.2, margin = margin(5, 0, 15, 0)), 
      #plot.caption = element_text(family = "techmono", size = 9, color = "white", hjust = 0.95)     #labels and final sizing
  )
)

ragg::agg_png(here::here("render", paste0("global_seafood_vulnerability", format(Sys.time(), "%Y%m%d_%H%M%S"), ".png")), 
              res = 320, width = 18, height = 8, units = "in")                                       #making png and telling it where to go

final                                                                                                #print final graph
  
dev.off()                                                                                            #render graph (?)
                             #RUN THIS WHOLE CHUNK AT ONCE OR IT WON'T WORK!!!

ggsave("4.a.Total_Seafood_Production_NE_2010_2020_Climate_Vulnerability.pdf", width = 15, height = 9)


```
